### ISSUE TITLE
Getting error in xtts_wav2lip.bat

### ISSUE THREAD

**Issue by gvzf** [Mozer/talk-llama-fast#36]
Did all by instructions, but I got an error:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\-\miniconda3\Lib\site-packages\xtts_api_server\__main__.py", line 56, in <module>
    from xtts_api_server.server import app
  File "C:\Users\-\miniconda3\Lib\site-packages\xtts_api_server\server.py", line 77, in <module>
    XTTS.load_model()
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\-\miniconda3\Lib\site-packages\xtts_api_server\tts_funcs.py", line 187, in load_model
    self.load_local_model(load = is_official_model)
  File "C:\Users\-\miniconda3\Lib\site-packages\xtts_api_server\tts_funcs.py", line 209, in load_local_model
    self.model.load_checkpoint(config,use_deepspeed=self.deepspeed, checkpoint_dir=str(checkpoint_dir))
  File "C:\Users\-\miniconda3\Lib\site-packages\TTS\tts\models\xtts.py", line 951, in load_checkpoint
    self.gpt.init_gpt_for_inference(kv_cache=self.args.kv_cache, use_deepspeed=use_deepspeed)
  File "C:\Users\-\miniconda3\Lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 223, in init_gpt_for_inference
    import deepspeed
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\__init__.py", line 22, in <module>
    from . import module_inject
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\module_inject\__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\module_inject\replace_module.py", line 587, in <module>
    from ..pipe import PipelineModule
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\pipe\__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\runtime\pipe\__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\runtime\pipe\module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\runtime\activation_checkpointing\checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\runtime\config.py", line 41, in <module>
    from ..elasticity import (
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\elasticity\__init__.py", line 10, in <module>
    from .elastic_agent import DSElasticAgent
  File "C:\Users\-\miniconda3\Lib\site-packages\deepspeed\elasticity\elastic_agent.py", line 9, in <module>
    from torch.distributed.elastic.agent.server.api import log, _get_socket_with_port
ImportError: cannot import name 'log' from 'torch.distributed.elastic.agent.server.api' (C:\Users\-\miniconda3\Lib\site-packages\torch\distributed\elastic\agent\server\api.py)`

![image](https://github.com/user-attachments/assets/8bd5a1ec-4e14-46d2-bcfa-d2f4a487c5da)

Maybe i need to update something?

**Comment by Mozer** [comment]
Maybe  you are using incorrect version of torch or Deepspeed. https://github.com/microsoft/DeepSpeed/issues/5337
What torch version you have?
